# Generated by Django 4.1.7 on 2023-03-08 05:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('aadhar_number', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(12), django.core.validators.MinLengthValidator(12)])),
                ('address', models.TextField()),
                ('profile_pic', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
