# Generated by Django 4.1.7 on 2023-03-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aadhar_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
